<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteForDataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>48e8369a-3880-4090-bc77-0578680a5abd</testSuiteGuid>
   <testCaseLink>
      <guid>c60d3f8f-8a55-48af-8881-2411979746c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day4/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c7291c49-024f-4ecc-85a6-4fb1ae9a89b6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c7291c49-024f-4ecc-85a6-4fb1ae9a89b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>705c338b-7a5f-4af1-be8c-e5048eddf7f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c7291c49-024f-4ecc-85a6-4fb1ae9a89b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6aec49bc-63fc-4477-a81e-9d4c5389b4ab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
